run:
  timeout: 7m

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  goimports:
    local-prefixes: sigs.k8s.io/custom-metrics-apiserver
  misspell:
    ignore-words:
      - "creater" # Cf. e.g. https://pkg.go.dev/k8s.io/apimachinery@v0.24.3/pkg/runtime#ObjectCreater
